### ISSUE TITLE
UI for download data

### ISSUE THREAD

**Issue by Gulfa** [who-emro/meerkat_frontend#28]
We need a UI for downloading csv files for various forms.

**Comment by mrjb** [comment]
This is basically ready to launch. Just need to know how to configure the config file. Namely, which attributes are to be considered "default" for each form.

**Comment by Gulfa** [comment]
For the case report these are the default fields: 
today,clinic,district,region,intro./visit_type,intro./module,pt./visit_date,pt1./status,pt1./gender,pt1./age,nationality,child_age,vaccination,vaccination_type,pc_mh,smoke_ever,smoke_now,icd_code

For the other forms we will provide all fields by default for now.
