### ISSUE TITLE
NCD Report

### ISSUE THREAD

**Issue by Gulfa** [who-emro/meerkat_frontend#37]
Create and NCD report

[MOH Jordan NCD Report Template.xlsx](https://github.com/who-emro/meerkat_frontend/files/138200/MOH.Jordan.NCD.Report.Template.xlsx)

**Comment by johnhaskew** [comment]
I have updated the codes file to include lab_1 to lab_5 variables to calculate BMI, BP, Fasting Glucose and HbA1c.

I'm not sure of the method, condition, category for each if you could please review.

Current smoking is already indicated.

Please note we don't have co-morbid conditions or complications in the forms, so it just shows as NA
