### ISSUE TITLE
Download Data UI

### ISSUE THREAD

**Issue by johnhaskew** [who-emro/meerkat_frontend#49]
Thanks guys for putting this up - it is great.

A few comments on the UI and functionality:
1. We should not include all forms or just show all raw data for download. It won't make any sense to anyone except us! For now, we just need to show the Case Report as available for download but can use other data downloads in future e.g. mhGAP, IMCI etc.
3. Please can we remove the "Just download the default attributes." option and simply display all variables using the multiple select box as the initial view.
4. Please can we remove all variables from the multiple select except for the basic set that are currently selected.
5. Could we include a single "All variables" option, just as we do with "All Alerts" to select all these basic variables or to select just a sub-selection
6. I realise it may need to come later, but would be also good to have a further filter window of option boxes to further filter to the data e.g just CD, NCD and for certain time periods too

I hope this makes sense? Please let me know if any clarifications are needed.

**Comment by johnhaskew** [comment]
Incidentally - I don't think we should share with MOH until the initial revisions are made as it will be confusing for them.

**Comment by johnhaskew** [comment]
"Avilable Attributes" header is mis-spelt. Please can we name as "Variables to Download"

**Comment by Gulfa** [comment]
I disagree with point 1. I think as a matter of principle we should let people download all the raw data and I really don't think it is that confusing. We can show the Case Report form as the first form in the list if we want. 

2-5 is fine.

We should discuss what we want to do about 6 at a later stage.

**Comment by johnhaskew** [comment]
The case report form contains innumerable within form calculations, which appear as separate variables include icd1_code, icd2_code, icd3_code, icd4_code etc not to mention all the calculations for CD, IMCI and mhGAP that are included. 

These have nothing to do with ICD, IMCI or mhGAP itself and is simply what we use internally to enable the skip logic algorithms and ensure the various modules are integrated together.

**Comment by Gulfa** [comment]
My proposal is as follows: 

We keep the dropdown box for all the forms, but display the Case Report form as the default choice. Then we display the box to select variables by default. This box will be default only include the default variables, but with a button at the bottom to show all available attributes. This way everything is available, but it should be very easy to just get the default variables.

**Comment by johnhaskew** [comment]
ok sounds good. Thanks Gunnar - I do agree with the principle everything should be transparent and available.

**Comment by johnhaskew** [comment]
Incidentally - the refugee data will need differential access, as many more partner will need to download this data but not have access to the other data. I hope this is possible.

**Comment by Gulfa** [comment]
We will work something out

**Comment by mrjb** [comment]
I'll try and make these changes this morning.

**Comment by mrjb** [comment]
This is done and pushed to master.
