### ISSUE TITLE
Naming of Reports

### ISSUE THREAD

**Issue by johnhaskew** [who-emro/meerkat_frontend#52]
Could we please change the name of the reports in the **Jordan cover page**, reports section from:
- Latest Communicable Disease Profile Report and
- Latest Non-Communicable Disease Profile Report 

Could we please just call them:
- Communicable Disease Profile 
- Non-Communicable Disease Profile 

And please change the names in the **Reports page **naming from:
-Communicable Disease Profile Reports
-Non-Communicable Disease Profile Reports
 
to:
-Communicable Disease Profile
-Non-Communicable Disease Profile

Finally in the **Reports** themselves to change the name to:
-Communicable Disease Profile
-Non-Communicable Disease Profile

**Comment by Gulfa** [comment]
I have changed this everywhere, but the Reports page. Here the word report is added automatically. Can you take a look Jonathan?

**Comment by mrjb** [comment]
This should be done and pushed to all country's configs. Will appear as sites are redeployed.
