### ISSUE TITLE
Periodicity of reports

### ISSUE THREAD

**Issue by johnhaskew** [who-emro/meerkat_frontend#71]
We currently generating cumulative reports by week since the start of year. It would be great to be able to  also generate reports for particular time periods e.g. by week or by month.

I defer to Jonathan as to how this functionality should be included as a UI!

Many thanks.

**Comment by Gulfa** [comment]
This should already work from the API side of things. We will need to think about what periodicity is sensible for each report and will need to rewrite the report function in the frontend.

**Comment by mrjb** [comment]
This should be done.
