### ISSUE TITLE
Download Data Function

### ISSUE THREAD

**Issue by johnhaskew** [who-emro/meerkat_frontend#72]
Dear All - we had a productive meeting with MOH about the system and went through the various new features added. Firstly - thank you for all the excellent work which is well received by MOH.

The Download Data works well but it is clear it is too confusing to simply have raw data from the forms to download. MOH don't understand what each variable means or where they come from.

If possible, we need to therefore restructure the download data function according to function - ie. CD, NCD, MH etc and to only include variables in each form that need to be used. We also need to rename the variables to something that can be understood to MOH.

I attach a data dictionary for seven data download files -**Communicable Disease, Non-Communicable Disease, Mental Health, PIP, IMCI, Nutrition and Vaccination and mhGAP**. The first column includes the current variable name, the second the name it should be renamed to and the third column contains the source form of the data (case, alert or review).

I hope this makes sense and is possible. I am happy to also include a **Raw Data** file for download too which includes the raw data for anyone who should need everything - ie. **Raw Data (Case Report), Raw Data (Daily Register) etc.**

**We also need to ensure the data can be downloads as .xls please** - there are problems downloading the csv for MOH (need to separate into columns manually).

[Public Health Surveillance | Data Dictionary.docx](https://github.com/who-emro/meerkat_frontend/files/161388/Public.Health.Surveillance.Data.Dictionary.docx)

**Comment by mrjb** [comment]
Making good progress with this. Will this look (very nearly) the same for all countries?
