### ISSUE TITLE
Hebrew text

### ISSUE THREAD

**Issue by johnhaskew** [who-emro/meerkat_frontend#77]
To please change the Mapbox Hebrew text (for Israel) to Arabic

**Comment by Gulfa** [comment]
At the moment we are using the same mapbox map settings for all countries. Is it alright if we use English text for all maps or do we need to create separate maps for each country?

**Comment by johnhaskew** [comment]
would be great to please enable different map box settings for different countries. we need all arabic for jordan and all french ideally for djibouti and madagascar. is this possible?

**Comment by Gulfa** [comment]
It is possible to have separate maps for each country, it just invloves more work. Unfortunately it does not look like mapbox supports Arabic as a language so we can either choose English or local(which is what we have atm, where we get Arabic in Jordan and Hebrew in Israel). French is supported.

**Comment by johnhaskew** [comment]
Ok, if Arabic is not supported then please can we just change all to English for now. It is not urgent to look into settings for each country right now.

**Comment by mrjb** [comment]
All sites should now have an entirely English map.
